// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevisionPlatform.Api.Data;

#nullable disable

namespace RevisionPlatform.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923031707_AddRevisionModules")]
    partial class AddRevisionModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RevisionPlatform.Api.Activities.RevisionActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_revision_activities");

                    b.ToTable("revision_activities", (string)null);
                });

            modelBuilder.Entity("RevisionPlatform.Api.Modules.RevisionModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_revision_modules");

                    b.HasIndex("ActivityId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_revision_modules_activity_id_position");

                    b.ToTable("revision_modules", (string)null);
                });

            modelBuilder.Entity("RevisionPlatform.Api.Themes.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_0900_as_ci");

                    b.HasKey("Id")
                        .HasName("pk_themes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_themes_name");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("activity_themes", b =>
                {
                    b.Property<int>("activity_id")
                        .HasColumnType("int")
                        .HasColumnName("activity_id");

                    b.Property<int>("theme_id")
                        .HasColumnType("int")
                        .HasColumnName("theme_id");

                    b.HasKey("activity_id", "theme_id")
                        .HasName("pk_activity_themes");

                    b.HasIndex("theme_id")
                        .HasDatabaseName("ix_activity_themes_theme_id");

                    b.ToTable("activity_themes", (string)null);
                });

            modelBuilder.Entity("RevisionPlatform.Api.Modules.RevisionModule", b =>
                {
                    b.HasOne("RevisionPlatform.Api.Activities.RevisionActivity", null)
                        .WithMany("Modules")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revision_modules_revision_activities_activity_id");
                });

            modelBuilder.Entity("activity_themes", b =>
                {
                    b.HasOne("RevisionPlatform.Api.Activities.RevisionActivity", null)
                        .WithMany()
                        .HasForeignKey("activity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_themes_revision_activities_activity_id");

                    b.HasOne("RevisionPlatform.Api.Themes.Theme", null)
                        .WithMany()
                        .HasForeignKey("theme_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_themes_themes_theme_id");
                });

            modelBuilder.Entity("RevisionPlatform.Api.Activities.RevisionActivity", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
